name: Lint and Test
on: push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
        cache: pip
        cache-dependency-path: requirements-dev.txt
        allow-prereleases: true
    - run: pip install -r requirements-dev.txt
    - uses: psf/black@stable
      with:
        options: "--check --verbose"
    - run: ruff check .
    - name: Run type checks
      run: |
        ty --version
        ty check .
