name: Lint and Test
on: push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
        cache: pip
        cache-dependency-path: requirements.txt
        allow-prereleases: true
    - run: pip install -r requirements.txt
    - run: black . --check --verbose
    - run: ty check ai_roi_mcm_npv.py npv_model.py params_pert.py --python "$pythonLocation"
    - run: ruff check .
    - run: python -m pytest
